### ISSUE TITLE
Restricting Quality

### ISSUE THREAD

**Issue by agpsn** [RandomNinjaAtk/docker-amd#10]
How do you only download FLAC. If it’s not available in FLAC but is in lower quality like MP3, how do you skip or not download?

**Comment by RandomNinjaAtk** [comment]
That's not supported at the moment.

**Comment by RandomNinjaAtk** [comment]
Added some new code and setting that should replicate what your looking for, give it a try after you've updated your image...

Also let me know if its working...

**Comment by agpsn** [comment]
It seems to still download the mp3 versions but then deletes them before lidarr imports them. So it’s good enough for me lol.
