### ISSUE TITLE
Doesn't Find anything

### ISSUE THREAD

**Issue by diabl0w** [RandomNinjaAtk/docker-amd#11]
Hi, I am not sure how to get this to work. If I add an artist in Lidarr, and then manually go in and run the bash script, AMD sees the artists properly but never finds anything. To reproduce, you can add "Eminem" into lidarr, choose lossless profile, choose existing albums, let it do its updating/searching, then go into AMD and manually run the script.
Example output: 
> 2 of 2 :: MBZDB CACHE :: Eminem :: Caching Musicbrainz Artist Info...
2 of 2 :: MBZDB CACHE :: Eminem :: Caching 398 releases...
2 of 2 :: MBZDB CACHE :: Eminem :: Downloading Releases page 0... (0 - 100 Results)
2 of 2 :: MBZDB CACHE :: Eminem :: Downloading Releases page 1... (100 - 200 Results)
2 of 2 :: MBZDB CACHE :: Eminem :: Downloading Releases page 2... (200 - 300 Results)
2 of 2 :: MBZDB CACHE :: Eminem :: Downloading Releases page 3... (300 - 400 Results)
Sleep 15 seconds to allow processes to complete
############################################ DOWNLOAD AUDIO (WANTED MODE)
Downloading missing list...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--100   140    0   140    0     0   6666      0 --:--:-- --:--:-- --:--:--  6666
FINDING MISSING ALBUMS: 0 Found
Downloading cutoff list...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--100   140    0   140    0     0   3684      0 --:--:-- --:--:-- --:--:--  3684
FINDING CUTOFF ALBUMS: 0 Found
############################################ DOWNLOAD AUDIO COMPLETE

**Comment by diabl0w** [comment]
I tried changing MatchDistance to 999, and still nothing

**Comment by diabl0w** [comment]
This seems to be a issue with lidarr instead, where it is removing all my wanted artists/albums from the missing list

**Comment by RandomNinjaAtk** [comment]
Your last comment sounds correct it can obviously communicate if it pulls the lists of artists but you missing list must not have any data. Probably an issue with your monitored album settings...
