### ISSUE TITLE
DockStarter

### ISSUE THREAD

**Issue by robgates** [RandomNinjaAtk/docker-amd#15]
I see you docker image is in Dockstarter but cant seem to get it to run , is this something you can look at ?

**Comment by RandomNinjaAtk** [comment]
I don't know what that is, so someone else may need to help on this one...

**Comment by zobe123** [comment]
https://github.com/GhostWriters/DockSTARTer/tree/master/compose/.apps/amd looks like a GUI for docker, looks interesting for me so i will take a look into it the next few days

**Comment by robgates** [comment]
Sorry yes I forgot to include the link to dockStarter

My Fault



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RandomNinjaAtk** [comment]
That is a completely separate project, so your time would be better spent reporting it to the correct github repo because that is not maintained here.
