### ISSUE TITLE
errors in Lidarr logs

### ISSUE THREAD

**Issue by jes1417** [RandomNinjaAtk/docker-amd#16]
seeing a lot of these errors in the lodarr logs and I am not sure why they are happening. 

![image](https://user-images.githubusercontent.com/38092747/91681449-1e648980-eb14-11ea-8b2b-c9b7fb31ac34.png)

I am running the latest linuxserver/lidarr:preview image 

```
About
Version 0.7.1.1784
Package Version 0.7.1.1784-ls18 by linuxserver.io
.NET Core Yes
Docker Yes
DB Migration 40
AppData directory /config
Startup directory /app/lidarr/bin
Mode Console

```

and also running the latest amd image.

**Comment by jes1417** [comment]
Well it is importing some albums but I guess it is throwing this error because lidarr dosent want to import them as they already exist.

![image](https://user-images.githubusercontent.com/38092747/91682928-c54b2480-eb18-11ea-872a-5e63616da9e7.png)

**Comment by jes1417** [comment]
It is grabbing and importing missing ones though.

![image](https://user-images.githubusercontent.com/38092747/91683035-11966480-eb19-11ea-8bc9-4d77d0f89f78.png)

**Comment by RandomNinjaAtk** [comment]
Your volume mapping is incorrect, read your first comment and the path given. To correct the error you need to map the AMD volume to lidarr

**Comment by jes1417** [comment]
I fixed that issues but I am still getting the errors

![image](https://user-images.githubusercontent.com/38092747/91733805-af1c8300-eb6f-11ea-8262-10243a66af58.png)
![image](https://user-images.githubusercontent.com/38092747/91733910-da06d700-eb6f-11ea-85f8-0b44bfecbcc1.png)
![image](https://user-images.githubusercontent.com/38092747/91734010-f86cd280-eb6f-11ea-97f9-d233e265cf0d.png)

**Comment by RandomNinjaAtk** [comment]
That doesn't show you fixed the path.... It still saying the folder does not exist... The folder would exist if you mapped the /downloads-amd volume...

**Comment by jes1417** [comment]
The path is accessible though? It's all under /data?

**Comment by RandomNinjaAtk** [comment]
Try reading the error again.... Does it say /data 125% sure it does not.....

**Comment by jes1417** [comment]
So for t he lidarr container I have  /data:/data as the path I also need to add /data/downloads-amd:/doownloads-amd

**Comment by jes1417** [comment]
Ok the errors are gone it looks like it's working, I guess I figured since they were all in the same path it would work.
