### ISSUE TITLE
How to setup "Lidarr Remote Path Mapping" (moving instead of copying)

### ISSUE THREAD

**Issue by ktrain1** [RandomNinjaAtk/docker-amd#18]
First off- I'm loving the latest features you've added into this. You've basically eliminated my need for beets entirely. I'm just having a hang up on one of the newest items though.

When it says-

> Configure this to the local volume path for Lidarr to see the downloads folder

I took that as the path for my actual Lidarr library folder. I was mistaken because the log is pulling errors saying it cannot find the folder and it's not moving (or copying) the downloads. 

It's probably obvious, but could you try explaining where it's actually suppose to be pathed?

**Comment by RandomNinjaAtk** [comment]
It works similar to Lidarr's remote path mapping feature. If you know how to configure lidarr's feature for that, it works the same way for the most part.

This feature in all the arrs people seem to struggle with and it's not a requirement for AMD but requires everything to be setup perfectly. The feature is not easy to outline or explain, but you can hop on discord if you want further help
