### ISSUE TITLE
[Request] Add Parameter to Specify Whether Explicit or Clean Version Is Preferred

### ISSUE THREAD

**Issue by TuRDMaN** [RandomNinjaAtk/docker-amd#19]
I don't know if this is possible already, but I'd love to see an option to specify whether the Clean or Explicit version of a release is preferred when both are found.

**Comment by RandomNinjaAtk** [comment]
By default explicit is preferred

**Comment by TuRDMaN** [comment]
> By default explicit is preferred

Yes, I've noticed that. But is there a way to set Clean versions as preferred?

**Comment by RandomNinjaAtk** [comment]
Rebooting the container wipes changes to the script, feel free to add a setting and write a PR for it...

**Comment by RandomNinjaAtk** [comment]
Would a clean only option work for this? That would be the simplest to implement most likley
