### ISSUE TITLE
Using quotes on certain environment variables breaks script

### ISSUE THREAD

**Issue by daPyr0x** [RandomNinjaAtk/docker-amd#2]
I'm not well versed with any of this, so it's possible this is my own lack of understanding.

Readme suggests that the environment variables within my docker-compose.yml should be as follows

```
environment:
      - PUID=118
      - PGID=1005
      - TZ=America/Toronto
      - UMASK_SET=002
      - AUTOSTART="true"
      - LidarrUrl="http://lidarr:8686/lidarr/"
      - LidarrAPIkey="redacted"
```

However the scripts fail to parse the AUTOSTART, LidarrURL, and LidarrAPIkey fields properly if quotes are used.  Below is what was needed to make the script operate.

```
environment:
      - PUID=118
      - PGID=1005
      - TZ=America/Toronto
      - UMASK_SET=002
      - AUTOSTART=true
      - LidarrUrl=http://lidarr:8686/lidarr/
      - LidarrAPIkey=redacted
```

**Comment by RandomNinjaAtk** [comment]
You need to pass all the env variables to the container.

**Comment by RandomNinjaAtk** [comment]
Feel free to pull request and correct the readme as needed or add wiki page with guidance for using docker compose.
