### ISSUE TITLE
Syntax for -e DOWNLOADMODE=artist

### ISSUE THREAD

**Issue by samcro1967** [RandomNinjaAtk/docker-amd#22]
Is the intent of this flag to allow users to specify an artist to search for missing albums?  If so, what is the syntax?  I tired the following, but it started with the first artist alphabetically in the Lidarr library rather than the one specified.

docker exec -it amd /bin/bash -c 'bash /config/scripts/download.bash artist_name'

**Comment by RandomNinjaAtk** [comment]
No, you just use the normal command given in the readme. Lidarr artists are processed automatically
