### ISSUE TITLE
Stuck forever when it can't find albumn/LP/Single

### ISSUE THREAD

**Issue by ElRoberto538** [RandomNinjaAtk/docker-amd#23]
I'm not sure if this is an issue with my Lidarr setup or not, but I have it set to download LPs and singles and I have about 400 in my wanted list that can't be found (which isn't an issue I kind of expected it wouldn't grab every random LP and single). My issue is that the AMD docker runs constantly in a loop looking for them and never gives up, so it takes longer and longer to find music that it will be able to download, and it uses a fair amount of CPU in the process (15-20% of my 4 cores 24/7).

Should it track attempts and stop trying after x attempts at the same search? Restarting the container/updating the container could clear the list for when new content becomes available.

Or am I missing something obvious that would resolve this issue without manually removing all of the failed downloads from my wanted list?

**Comment by RandomNinjaAtk** [comment]
It's always going to process the entire list. However, I may be able to speed it up to skip ones that were not found previously. 

I'll look into what the script is doing and implement something a little better to handle that. It won't solve checking them every run, but it should speed it up.

**Comment by RandomNinjaAtk** [comment]
Question, are you not seeing messages in the log that state something like this?

"PREVOUSLY NOT FOUND SKIPPING..."

Because it should be skipping searches for albums already not found and outputting that message in the log...

**Comment by ElRoberto538** [comment]
Huh, I just restarted the docker container, you are correct, it is saying that. Looks like something else is going on - it's finding the albums after doing fuzzy match but it's already downloaded - just Lidarr is not importing it so it isn't dropping off my wanted list... therefore when it checks my list again it sees it's still wanted and tries to find it again using fuzzy match and repeats from there. That was all the errors I was seeing. Once it's downloaded sucessfully, should it add it to the "do not check" list?

I can submit a PR at some point if you think that is an appropriate solution? I'm guessing Lidarr isn't importing them due to it not being an exact match - not sure what the fix there would be?

**Comment by RandomNinjaAtk** [comment]
Any PR is welcome if you have better ideas on it.

The only way to possibly help matching would be to improve the musicbrainz database with better info that more closely matches. But even then, it could still be rejected.

**Comment by ElRoberto538** [comment]
OK, I'll look more into how Lidarr/AMD works later in the week and see what I can come up with, If I find a good solution I'll submit a PR, thanks for the assist with this (and AMD)!
