### ISSUE TITLE
Lidarr not recognizing files in the import folder

### ISSUE THREAD

**Issue by azumukupoe** [RandomNinjaAtk/docker-amd#25]
files in dlclient gets recognized alright so there's something about post processes that makes files unrecogniziable for Lidarr

**Comment by RandomNinjaAtk** [comment]
Could be related to your other issue, idk...

You could modify the script to remove the processes that modify the files.

Such as here:
https://github.com/RandomNinjaAtk/docker-amd/blob/f922cd9d5a857094f522c56b3dd53429c0947001/root/scripts/download.bash#L1214

And here:
https://github.com/RandomNinjaAtk/docker-amd/blob/f922cd9d5a857094f522c56b3dd53429c0947001/root/scripts/download.bash#L1800

**Comment by azumukupoe** [comment]
I did some testing just now and can verify that the files become unrecognizable by Lidarrr after `FIXING TAGS :: *.mp3 fixed...`
Could you add an option to disable the process or even make the process optional?

**Comment by RandomNinjaAtk** [comment]
After the new image update is out, give the new changes a try @azumukupoe

**Comment by azumukupoe** [comment]
Running the script with - ENABLEPOSTPROCESSING=false
Still not importing :(

**Comment by azumukupoe** [comment]
I copied the album folder from import folder to dlcient folder and Lidarr seems to recognize the files, so maybe it's not about the tags

**Comment by RandomNinjaAtk** [comment]
The only thing I think it could be is that your docker config is not correct for lidarr. You can try getting extra help on discord.

You may want to turn on trace logs for lidarr and see what happens when it attempts to import.

**Comment by azumukupoe** [comment]
from the trace log
```
20-11-5 01:46:49.6|Trace|Http|Req: 9661 [POST] /api/v1/command
20-11-5 01:46:49.6|Trace|CommandQueueManager|Publishing DownloadedAlbumsScan
20-11-5 01:46:49.6|Trace|CommandQueueManager|Checking if command is queued or started: DownloadedAlbumsScan
20-11-5 01:46:49.6|Trace|CommandQueueManager|Inserting new command: DownloadedAlbumsScan
20-11-5 01:46:49.7|Trace|Http|Res: 9661 [POST] /api/v1/command: 201.Created (113 ms)
20-11-5 01:46:49.7|Trace|CommandExecutor|DownloadedAlbumsScanCommand -> DownloadedAlbumsCommandService
20-11-5 01:46:49.7|Trace|CommandQueueManager|Marking command as started: DownloadedAlbumsScan
20-11-5 01:46:49.7|Debug|Api|[POST] /api/v1/command: 201.Created (113 ms)
20-11-5 01:46:49.8|Trace|Http|Req: 9662 [GET] /api/v1/album?albumIds=549
20-11-5 01:46:49.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-11-5 01:46:49.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-11-5 01:46:49.8|Trace|Http|Res: 9662 [GET] /api/v1/album?albumIds=549: 200.OK (41 ms)
20-11-5 01:46:49.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-11-5 01:46:49.8|Debug|Api|[GET] /api/v1/album?albumIds=549: 200.OK (41 ms)
20-11-5 01:46:49.8|Debug|Parser|Parsing string 'Kate Bush - 50 Words for Snow (2011)-WEB-album-deemix'
20-11-5 01:46:49.9|Trace|Parser|^(?:(?<artist>.+?)(?: - )+)(?<album>.+?)\W*(?:\(|\[)(?<releaseyear>\d{4})
20-11-5 01:46:49.9|Debug|Parser|Album Parsed. Kate Bush - 50 Words for Snow 
20-11-5 01:46:49.9|Debug|QualityParser|Trying to parse quality for Kate Bush - 50 Words for Snow (2011)-WEB-album-deemix
20-11-5 01:46:49.9|Debug|Parser|Quality parsed: Unknown v1
20-11-5 01:46:50.0|Debug|Parser|Release Group parsed: deemix
20-11-5 01:46:50.0|Debug|Parser|Parsing string 'Kate Bush - 50 Words for Snow (2011)-WEB-album-deemix'
20-11-5 01:46:50.0|Trace|Parser|^(?:(?<artist>.+?)(?: - )+)(?<album>.+?)\W*(?:\(|\[)(?<releaseyear>\d{4})
20-11-5 01:46:50.0|Debug|Parser|Album Parsed. Kate Bush - 50 Words for Snow 
20-11-5 01:46:50.1|Debug|QualityParser|Trying to parse quality for Kate Bush - 50 Words for Snow (2011)-WEB-album-deemix
20-11-5 01:46:50.1|Debug|Parser|Quality parsed: Unknown v1
20-11-5 01:46:50.1|Debug|Parser|Release Group parsed: deemix
20-11-5 01:46:50.1|Debug|DownloadedTracksImportService|Kate Bush - 50 Words for Snow (2011)-WEB-album-deemix folder quality: Unknown v1
20-11-5 01:46:50.2|Debug|DiskScanService|Scanning '/downloads-amd/amd/import/Kate Bush - 50 Words for Snow (2011)-WEB-album-deemix' for music files
20-11-5 01:46:50.3|Trace|DiskScanService|1 files were found in /downloads-amd/amd/import/Kate Bush - 50 Words for Snow (2011)-WEB-album-deemix
20-11-5 01:46:50.3|Debug|DiskScanService|0 audio files were found in /downloads-amd/amd/import/Kate Bush - 50 Words for Snow (2011)-WEB-album-deemix
20-11-5 01:46:50.3|Debug|ImportDecisionMaker|Analyzing 0/0 files.
20-11-5 01:46:50.3|Debug|ImportApprovedTracks|Importing 0 files. replaceExisting: True
20-11-5 01:46:50.4|Debug|ImportApprovedTracks|Inserted new trackfiles in 0ms
20-11-5 01:46:50.4|Debug|ImportApprovedTracks|TrackFileIds updated, total 27ms
```

**Comment by RandomNinjaAtk** [comment]
Did you check the folders to see if the files were in there?

If they are, you may have a permissions issue.

**Comment by azumukupoe** [comment]
I have them default in docker-compose.yml
```
      - FolderPermissions=766
      - FilePermissions=666
```

**Comment by RandomNinjaAtk** [comment]
Try to manual import from that same folder location, not moving it. If you can, then its not a permission issue

If you can't that might explain why lidarr is complaining

**Comment by azumukupoe** [comment]
I can only see the files when they are in dlclient folder

**Comment by RandomNinjaAtk** [comment]
the files should be in the import folder? if they are not, that is your issue

**Comment by azumukupoe** [comment]
I can see the files in lidarr only when I move them from import folder to dlclient folder

**Comment by RandomNinjaAtk** [comment]
Sounds like a permission issue, try changing the permissions of the files to 777 manually and then seeing if lidarr can see them

**Comment by azumukupoe** [comment]
Two folders have the same set of permissions
```
drwxrw-rw- 1 abc abc 4096 Nov  5 02:10 dlclient
drwxrw-rw- 1 abc abc 4096 Nov  5 02:10 import
```

You mentioned only testing with Linux systems
perhaps your script doesn't work well with Windows?

**Comment by azumukupoe** [comment]
Lidarr started importing after changing their permission to 777
Maybe you should change them to 777 in the example snippets?
After all, it wasn't about the tag fixes

**Comment by RandomNinjaAtk** [comment]
Permissions are super insecure at 777, so the defaults a more secure, but obviously different setups require different needs.

Glad this is resolved.
