### ISSUE TITLE
Not finding artists in artist mode

### ISSUE THREAD

**Issue by Maerchensarg** [RandomNinjaAtk/docker-amd#26]
Hi. I am playing around with the docker-compose file and for now it looks pretty good, except one thing:

2020-10-30 17:38:19 :: 3 of 4 :: ARTIST_NAME_HERE :: ERROR :: Deezer Artist ID not found...

The artist is available on deezer. Other artists are working fine. Any idea?

**Comment by Maerchensarg** [comment]
Thanks for the info. I did not noticed it. Can you say how long an "update" takes after setting the link?
And thanks for your nice work.

**Comment by RandomNinjaAtk** [comment]
Should be immediately if not using a mirror for musicbrainz

**Comment by Maerchensarg** [comment]
Sorry for all the questions but must only the link to the deezer artist page "https://www.deezer.com/artist/123456789" be set in the relations page? So the entry "stream for free" on musicbrainz is available? 
Set it but somehow amd is still not finding the artist IDs.

**Comment by RandomNinjaAtk** [comment]
I lied, was going by memory, after brief review of the code, you need to wait for lidarr to have the updated info. Lidarr syncs with musicbrainz 5-10 min past every hour.

The. You need to refresh the artist locally in lidarr to pull the new data.

**Comment by Maerchensarg** [comment]
Hm, its still struggeling. I deleted the old config folder and get no new log about updating the musicbrainz page but I still get 

ERROR :: Deezer Artist ID not found...

I refreshed lidarr as well and the deezer link is showing up on lidarrs artist page. But amd is still not able to find the artist on deezer.

**Comment by cruix89** [comment]
This happens when the artist has no Deezer link on musicbrainz, go to the artist page on musicbrainz and make an edit, adding the artist link on deezer

**Comment by Maerchensarg** [comment]
Can confirm this working for one out of five. Created a fresh lidarr and amd instance today and amd is still not able to find the deezer-ID for some artists. The musicbrainz artist page got the correct deezer link. Will wait some more time to see what happens.

If I add the deezer link to musicbrainz before adding the artist to lidarr, everything seems to work fine (I wait about an hour before I start amd).

**Comment by RandomNinjaAtk** [comment]
You need to provide links to musicbrainz artist and the service links so I thers can test to reproduce the problem. If cannot be reproduced, cannot be fixed

**Comment by Maerchensarg** [comment]
For example this is still not working after adding the link after your first post here.

https://musicbrainz.org/artist/0bcf6f8b-bbe1-4571-b887-e2cc93437484
https://www.deezer.com/en/artist/1174045

**Comment by Maerchensarg** [comment]
Cannot reproduce it. Thanks everyone.
