### ISSUE TITLE
[Feature request] Filtering releases older than X days ?

### ISSUE THREAD

**Issue by SebNYD** [RandomNinjaAtk/docker-amd#27]
Hello,

The script is wonderful, so thanks a lot for this :)

I do however have a feature request. Lidarr is often picking up old releases (especially singles) that just have been added to MusicBrainz.
Would it be possible to have a feature that would ignore releases older than x days (or something similar) ?

Thanks,

**Comment by RandomNinjaAtk** [comment]
No, lidarr controls amd, so if you don't want them, remove them from lidarr.
