### ISSUE TITLE
script starting before the lidarr

### ISSUE THREAD

**Issue by cruix89** [RandomNinjaAtk/docker-amd#28]
hello dear RandomNinja, on my docker the lidarr is a little slow to start, everything is ok but it is a little slow, with that, AMD starting before the lidarr and the error with the following line:

ERROR: Cannot communicate with Lidarr, no response

Please correct errors before attempting to run script again ...

Exiting ...

would it be possible for you to add a condition for the script to automatically restart when this happens?

since already thank you very much

**Comment by lmarianski** [comment]
you can just add `restart: always` or `restart: unless-stopped` to the docker-compose, docker will restart the container if it exits.

**Comment by cruix89** [comment]
will try thanks

**Comment by cruix89** [comment]
> you can just add `restart: always` or `restart: unless-stopped` to the docker-compose, docker will restart the container if it exits.

just leaving a feedback from the friend's tip, it didn't work, the script doesn't restart with the docker compose "always"

**Comment by RandomNinjaAtk** [comment]
@cruix89 - when you get the image update from the last change v1.5.34, give it a try and see if it fixes it.

**Comment by RandomNinjaAtk** [comment]
This should be fixed, from my testing, please verify @cruix89

**Comment by cruix89** [comment]
> This should be fixed, from my testing, please verify @cruix89

updated and tested, it worked perfectly, that was what was missing, thank you, you are in fact a ninja :)
