### ISSUE TITLE
failing to match albums with the same artist/title found in deemix's search result

### ISSUE THREAD

**Issue by azumukupoe** [RandomNinjaAtk/docker-amd#30]
```
Kate Bush :: f857c209-1a7d-45dd-97cc-62c30b91be01 :: Director's Cut
Kate Bush :: de560c24-95c1-3b5b-b76f-0a0730b18134 :: The Red Shoes
```
in notfound.log despite albums with exact same the artist/title shows up in deemix's search results.

![image](https://user-images.githubusercontent.com/31339007/98202188-d418e200-1f74-11eb-9156-8c4a83ce600c.png)
![image](https://user-images.githubusercontent.com/31339007/98202265-fc084580-1f74-11eb-87c6-1789b2ebe755.png)

**Comment by RandomNinjaAtk** [comment]
That is not enough information to have any idea of what's going on. The matching in general, isn't perfect, if you can improve it, PR welcome
