### ISSUE TITLE
import folder content deletion

### ISSUE THREAD

**Issue by megadesk** [RandomNinjaAtk/docker-amd#33]
Upon a restart of the script the import folder's content is deleted.

Using in docker on synology system.

**Comment by RandomNinjaAtk** [comment]
This is normal, data is periodically wiped when cannot be imported.

**Comment by megadesk** [comment]
But why? If it can't be imported, I want to manually import it and not have wasted an entire day running the script only to return and see everything deleted. At the very least we should be able to decide if it deletes the content on subsequent runnings?

**Comment by abenfield** [comment]
I agree with megadesk. I ran the docker container yesterday and it downloaded several files then today I decided to run the script again. To my surprise, I noticed many album folders were removed from the import folder.

Is there a way to prevent this behavior in the current implementation? 

I also noticed upon re-running this script that it skips over previously downloaded albums, including the ones that were downloaded prior but didn't import and were deleted. Is this intended behavior?

Love the project and seeking answers to these issues.

**Comment by RandomNinjaAtk** [comment]
If item was not imported it, that means lidarr could not match it. The contents are wiped to prevent items failing to be matched/imported from filling your drive by sitting there forever.

The script is designed to be automated and not require user intervention, hence the cleanup.

That is also why it won't download a previously downloaded item.

**Comment by abenfield** [comment]
I can understand that. That you for taking the time to reply. I appreciate it. 

This might be off-topic, I can open a separate issue if desired. I was wondering if I used non-docker lidarr with amd whenever the amd script tells lidarr to import from directory, will it tell it to import from the host directory or the mapped directory?

If it's telling lidar to import from the mapped directory then it won't find it so that could be why it's failing to import.

**Comment by RandomNinjaAtk** [comment]
That could likely be an issues it's only really designed to work with lidarr that is also in a container.


If you want to see what's happening in lidarr, turn up the logging and watch lidarr to attempt to import and look for errors.
