### ISSUE TITLE
wrong album artwork is sometimes downloaded

### ISSUE THREAD

**Issue by megadesk** [RandomNinjaAtk/docker-amd#34]
The correct artwork is embedded in the file, yet the saved cover file is a mismatch.

I'd say < 5% of the albums suffer from this, and just as an example the artwork for Led Zeppelin's Houses of the Holy was included with America - History America s Greatest Hits.

**Comment by RandomNinjaAtk** [comment]
This is more likely a lidarr issue.

**Comment by megadesk** [comment]
How would it be a lidarr issue? The incorrect album artwork file is downloaded _before_ any import via lidarr.

**Comment by RandomNinjaAtk** [comment]
Local album art is extracted from the embedded artwork. However, lidarr will not import local artwork files. So local artwork in your lidarr library folders is only from lidarr. That's why it's a lidarr issue. Lidarr does not import extras properly.

**Comment by megadesk** [comment]
sure that makes sense. Maybe there is a miscommunication in what I'm trying to describe...

during the downloading process, before importing into lidarr, there are wrong cover photos in the respective album folders. e.g. `/amd/import/album_name` would have the incorrect album cover in the album_name folder. however it isn't just any wrong album art, it seems to be one of the album covers of a previously finished download.

so perhaps the extraction is pulling from the wrong file?

**Comment by RandomNinjaAtk** [comment]
I think this was resolved in latest script updates, be sure you update and retry and report back if this is resolved or not.
