### ISSUE TITLE
Infinite Loop on Led Zeppelin IV

### ISSUE THREAD

**Issue by megadesk** [RandomNinjaAtk/docker-amd#35]
the script seems to enter an infinite loop when searching for Led Zeppelin IV and it is not found

**Comment by RandomNinjaAtk** [comment]
You probably just need to wait longer....

**Comment by megadesk** [comment]
perhaps, I'll try to experiment again. Would it be normal for it to take over 4 hours?

**Comment by RandomNinjaAtk** [comment]
Idk, possibly, the matching process takes a long time and I don't use it. Greatly depends on the number of results it has to process. 

If it works normally for others then there is no indication of an issue, you just need to wait...

**Comment by megadesk** [comment]
thanks! I'll try disabling fuzzy and see how it goes.

**Comment by RandomNinjaAtk** [comment]
Please try the latest updates, and see if this is still an issue.

**Comment by RandomNinjaAtk** [comment]
I'm not able to reproduce the issue.
