### ISSUE TITLE
find: unrecognized: -iregex BusyBox v1.31.1 () multi-call binary.

### ISSUE THREAD

**Issue by samcro1967** [RandomNinjaAtk/docker-amd#38]
Started getting this error in the past couple of days after pulling the latest image.

```
find: unrecognized: -iregex
BusyBox v1.31.1 () multi-call binary.

Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]

Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'

	-L,-follow	Follow symlinks
	-H		...on command line only
	-xdev		Don't descend directories on other filesystems
	-maxdepth N	Descend at most N levels. -maxdepth 0 applies
			actions to command line arguments only
	-mindepth N	Don't act on first N levels
	-depth		Act on directory *after* traversing it

Actions:
	( ACTIONS )	Group actions for -o / -a
...
```

**Comment by tempestnano** [comment]
I believe this is caused by you still having the scripts folder mapped (default from previous version of AMD), so you are running the scripts from the old version. Try removing that directory bind and let us know if it fixes it.

**Comment by samcro1967** [comment]
Do you mean the scripts folder created in the AMD config folder when it is first run?  The only folder I am mounting to the image is the config folder.

If I delete that folder, a new one is not created and it fails with no script directory found.  Here is what is in that folder.

![image](https://user-images.githubusercontent.com/2319445/102231935-26261f00-3eb4-11eb-907f-47eb247e41bd.png)

**Comment by tempestnano** [comment]
Yeah, then that drive is definitely being mounted inside the container. Just remove that mounting, and you will be good. It might be easier to just remove and recreate the container.

**Comment by samcro1967** [comment]
I removed the mount from my docker command (-v C:\Users\user1\Documents\Docker\amd:/config) and am still getting the following:

docker exec -it amd /bin/bash -c "bash /config/scripts/download.bash"
bash: /config/scripts/download.bash: No such file or directory

It also then creates a volume that is orphaned on container exit.

**Comment by RandomNinjaAtk** [comment]
Is this still an issue, updated the readme accordingly
