### ISSUE TITLE
Deezloader alternative?

### ISSUE THREAD

**Issue by eringuet** [RandomNinjaAtk/docker-amd#39]
Hi, I was trying to install this and searching for ARL_TOKEN=ARLTOKEN and the link from the readme is dead. I'm guessing deezloader is no more but I see the latest commit here was 9 days ago. Is this still working? Thanks.

**Comment by RandomNinjaAtk** [comment]
Not aware of any issues, look online for how to get your token.

**Comment by eringuet** [comment]
Pretty simple once you figure out that the token comes from Deezer.

**Comment by Protektor-Desura** [comment]
https://deezloader.site/
There are directions here on how to get your ARL from a couple of different browsers.

**Comment by SimonRiley1001** [comment]
The video is private sadly![Screenshot_20210421-084328.png](https://user-images.githubusercontent.com/68485387/115516081-af43cd00-a27d-11eb-95dc-cd5ea1dbad92.png)

**Comment by SimonRiley1001** [comment]
![Screenshot_20210421-094447.png](https://user-images.githubusercontent.com/68485387/115524737-56c4fd80-a286-11eb-8a99-fe7bb58533d0.png)
It worked thank you Soo much
