### ISSUE TITLE
"ERROR:DOWNLOADS setting invalid", "Expected Valid Setting: /your/path/to/music/downloads

### ISSUE THREAD

**Issue by NovaCyntax** [RandomNinjaAtk/docker-amd#40]
Running in a Docker container on Synology NAS. Script infinitely loops attempting to restart itself, giving the errors in the title. My relevant parameters are as follows:

Mounted volumes:
`docker/Media/Music : /music` Music collection
`docker/data : /data` Download location for Transmission client
`docker/amd/config : /config` AMD config location

I have attempted mounting folders in `docker/Media/Music/downloads : /downloads`, as well as a folder named `docker/downloads : /downloads`. Both of these configurations failed to rectify the error. My variables are based on the examples given in the README.

What exactly am I doing wrong? The only variables I omitted are the Plex ones.

**Comment by RandomNinjaAtk** [comment]
Well you didn't follow the configuration guidelines, see here:
https://github.com/RandomNinjaAtk/docker-amd#parameters

The volume for downloads is called "downloads-amd", not "downloads"...

So in your example it should be, `docker/downloads : /downloads-amd`

**Comment by NovaCyntax** [comment]
This fixed my issue, thanks. I'd tried that before but must've forgotten when I reinstalled.
