### ISSUE TITLE
Nothing happens 

### ISSUE THREAD

**Issue by mboerma** [RandomNinjaAtk/docker-amd#41]
This sound and looks like such a great script. Easy setup with Docker-compose. All seems to work great. But at some point it stop to do anything. After this message in the log is just stops. I waited for a couple of hours. I don't see anything happening in the cache folder or the dl folder.

> 2020-12-29 17:24:07 :: 2 of 23800 :: Michael Kiwanuka :: 2019 :: Album :: KIWANUKA :: DOWNLOADING :: KIWANUKA :: https://deezer.com/album/116581812...
INFO:deemix:Linux-4.4.59+-x86_64-with - Python 3.8.5, deemix 2.0.5

**Comment by RandomNinjaAtk** [comment]
Looks like your not using the latest code/cleint, make sure you update your docker image, your version should be 2.0.10 for the dl client.

**Comment by mboerma** [comment]
At the time (29/12) this was the latest version of the docker image. I use watchtower to update the images. I see it grabbed a laters version 3 hours ago. I wil check if that works. The previous version did work on Mac with Docker.

**Comment by RandomNinjaAtk** [comment]
Could also be that your ARL token expired. I'm not aware of anyway to check/test that....

**Comment by mboerma** [comment]
The normal command line version works with this ARL. But let me see if this newer version of the image works. It sometimes takes a while before it kicks off the actual deemix command.

**Comment by mboerma** [comment]
Same thing with the newest version.

> INFO:deemix:Linux-4.4.59+-x86_64-with - Python 3.8.5, deemix 2.0.10
INFO:deemix:Generating queue item for: https://deezer.com/album/185143072

**Comment by RandomNinjaAtk** [comment]
Sounds like your having an issue with the DL client. You should report it there. Everything is working from my test setup. So its either something particular to your configuration that is causing it. If I cannot reproduce it, then it cannot be investigated....

**Comment by RandomNinjaAtk** [comment]
Sorry, not much I can do to help then.

**Comment by mboerma** [comment]
Apparently not. I don't think the other people will be able to help me either since they will say that their software works when you use it from the command line. Thanks for the script and container. I will have to see how I can fix it myself.

**Comment by RaymondSchnyder** [comment]
Same here, built the dockerimage myself. 
@mboerma did you manage to fix it?

**Comment by mboerma** [comment]
@RaymondSchnyder Nope.

**Comment by RaymondSchnyder** [comment]
https://git.rip/RemixDev/deemix/-/issues This seems to be the upstream project

EDIT: I think i found the problem. Somehow the container sets a weird DNS in /etc/resolv.conf
Changing it to the host dns settings works.
