### ISSUE TITLE
cpu usage seems limited in docker

### ISSUE THREAD

**Issue by drFDC** [RandomNinjaAtk/docker-amd#42]
Hi,
The CPU that amd is able to use seems limited to one core.
CPU Usage within the limits for cgroup amd (cgroup_amd.cpu_limit)
So I have 4 cores and it never goes above 25% (100% on one core, but switches between cores)
Is there a reason for this?

**Comment by RandomNinjaAtk** [comment]
This is a simple bash script, bash by nature is single threaded, hence only one core is used for the majority of tasks...
