### ISSUE TITLE
How to process with Beets container before Lidarr import

### ISSUE THREAD

**Issue by samcro1967** [RandomNinjaAtk/docker-amd#43]
Wondering if you are aware of any way to have Beets process the music before it is sent to Lidarr for import.  I have beets and Lidarr both running in separate containers from linuxserver and have not been able to find a way to have Lidarr call beets from a container on import.  Wondering if there is a way to do it from the amd container.

**Comment by RandomNinjaAtk** [comment]
You would need to fork and modify the docker and script to do that

**Comment by samcro1967** [comment]
I found a way to load the docker client into a container without modifying the container, but the method no longer seems to work as the beets_import.sh scripts fails to read /dev/core when it is called.  Guessing some updates to Docker over the past year have broken that method.

I was trying to avoid creating my own container to get the workflow running.  I think you are right that the only way to get it to work would be to create one container with Lidarr, Beets, and AMD all in it for the workflow to work correctly.

[Beets + Lidarr](https://www.reddit.com/r/Lidarr/comments/c1enh9/beets_lidarr/)
