### ISSUE TITLE
Some albums "already downloaded" but not imported into Lidarr?

### ISSUE THREAD

**Issue by CorneliousJD** [RandomNinjaAtk/docker-amd#44]
Hi there, first off I want to say THANK YOU. This makes things so SO easy with Lidarr right now.

I have a few albums in the log that show "already downloaded" but they weren't imported into Lidarr.

I already have them as MP3 V0's but it's not updated to FLAC. 

```
temp-lidarr-cutoff.j 100% |********************************| 457k 0:00:00 ETA
'/scripts/temp-lidarr-cutoff.json' saved
2021-01-20 09:51:52 :: FINDING CUTOFF ALBUMS: 34 Found
2021-01-20 09:51:54 :: 1 of 104 :: Empire of the Sun :: 2016 :: Album :: Two Vines :: SEARCHING...
2021-01-20 09:51:54 :: 1 of 104 :: Empire of the Sun :: 2016 :: Album :: Two Vines :: Already Downloaded
```

They do not exist in the /downloads-amd/amd/dlclient or /downloads-amd/import

Not sure how to make this re-search for them, or even why it downloaded but didn't import, or why it *thinks* it downloaded them in the first place?

Also, side question, if something is not avaialble, is there a timeout before it searches again? E.g. what if a new album is coming out, not available yet, but drops in 2 months, but it already searched and said it's not avaialbe, does it re-search once a week, once a day, etc? 

Thanks in advance!

**Comment by RandomNinjaAtk** [comment]
See #33

**Comment by CorneliousJD** [comment]
Rgr that, thanks! I can manually snatch those with Deemix and do a manual import instead, still automating 95% plus of my stuff right now with this, so cannot complain :) 

Appreciate the reply and thanks agian for all the work on this, truly amazing to use.
