### ISSUE TITLE
Search again for previously searched albums 

### ISSUE THREAD

**Issue by cactushydrocodone** [RandomNinjaAtk/docker-amd#46]
Hi,

I would like the script to search again for albums after a specific amount of time.
I checked the script, if theres a file named after the albumid, it will not be checked again. Ever.
Would it be possible to integrate a mechanism that tries to search for albums again, after, lets say, 3 weeks or 3 months?

As a workaround, its also possible to run a cronjob that runs daily and removes files in the directory where those ignorefiles are stored if they are older than a certain threshold.

**Comment by jdtorrenegraneiu** [comment]
1+ to this one.

**Comment by gnouts** [comment]
As I understand this issue, AMD stores locally which artists it has already searched. Instead of a another cronjob/timebased re-search, wouldn't it be better to lookup for missing album directly from Lidarr ? Each search should be run against all wanted albums.

> As a workaround, its also possible to run a cronjob that runs daily and removes files in the directory where those ignorefiles are stored if they are older than a certain threshold.

Not sure of my english here... Do you mean this could be an alternative implementation, or it's already an existing workaround I could use ? If the later, I'd like you tell more about it :D

**Comment by JesterEE** [comment]
I think this would be useful.  My solution now is to brute force it by blowing away all the config files, restart amd, and have it rebuild them from environment variables so that none of the search/cache history is there.  Less than ideal.

**Comment by therealklanni** [comment]
I have to agree with @gnouts here, that would be the ideal functionality. 

But it would be also useful (for some, I assume) to have "never retry previously searched" as a setting (ideally an opt-out, i.e. defaults to searching again unless you opt-out with the setting).

**Comment by tiagodj** [comment]
I use AMD to monitor the "wanted" list in lidarr. In my case, Wanted is most of the time Empty. So one way to implement this feature would be to do Whatever is in the Wanted list. even if it's an album previously searched.

Of course, we don't want it to keep downloading the same album over and over again if it did download but import failed into lidarr failed for other reasons. So there's this to consider.

**Comment by berto0** [comment]
Hello,
Thank you first for this magnificent project.

I can't get AMD to download the albums it has previously searched for for me. I have looked for the file "temp-lidarr-missing.json" to delete the albums already searched, but I have not found such a file in the config of AMB or Lidar.
Could you tell me a way to solve this problem?
Thanks

Translated with google translate.

**Comment by RandomNinjaAtk** [comment]
Purge the log directory "/config/logs"

**Comment by berto0** [comment]
> 
> 
> Purge the log directory "/config/logs"

It worked, thank you very much

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
