### ISSUE TITLE
Lidarr does not detect downloads for import

### ISSUE THREAD

**Issue by NotAUsername4Sure** [RandomNinjaAtk/docker-amd#47]
For the past 65 minutes i am trying to make Lidarr connect with your script but i am unable to automatically import anything. Everything goes straight to the amd/import folder. Is there any extra settings i need to make in Lidarr ? I have already applied the "Media Management Settings", also i tried going to Library->import and mapped the amd folder as a root folder. The "-v /downloads-amd" variable is exactly the same as Deluge, and Deluge is detected by Lidarr. I also tried mapping the dl-client folder or the import folder independently. Nothing seems to be able to auto import the songs.

**Comment by BertVereecken** [comment]
I have the same problem. Can't seem to find a way to tell Lidar to take the filer under /amd/import.
Everything  downloads perfectly, except Lidarr doesn't pick it up.

**Comment by NotAUsername4Sure** [comment]
I figured this out, It is not clearly stated in the documentation but you must use the exact volume mounting as described below.

A new folder will be created named "amd", in the folder you declare for downloads in your amd configuration (-v /downloads-amd).
You must mount that folder in as /downloads-amd/amd in your Lidarr container.
i.e.
I declare "/home/user/downloads" in amd configuration
After the amd container runs at least one time, a new folder must be present in "/home/user/downloads" named amd
So my new extra Lidarr volume mount will be "/home/user/downloads/amd:/downloads-amd/amd"

After that change everything works as expected.

As i understand, this is the case because the script is using a fixed path to for importing to Lidarr. This is seen in the event log in Lidarr's WebUI :
DownloadedAlbumsCommandService | Folder/File  specified for import scan [/downloads-amd/amd/import/Folder] doesn't exist.

Other than that the script works great, thanks goes to the dev.

**Comment by RandomNinjaAtk** [comment]
Glad you figured it out, but the description for the volume Mount point does instruct you to add it to lidarr container

https://github.com/RandomNinjaAtk/docker-amd#parameters

**Comment by JesterEE** [comment]
I agree, this was confusing for me too until I found https://github.com/RandomNinjaAtk/docker-amd/issues/47#issuecomment-784953697 and there's not really a better way to describe in one statement what to do. 

It may make it clearer to add that both the Remote Path **AND** Local Path must be _/downloads-amd/_.  I just thought that they needed to reference the same root directory on the host, but that wasn't it.

**Comment by jakemoritz** [comment]
I ran into this issue but I am not using Lidarr via Docker. Is it possible to properly mount the download directory to Lidarr if it is not running via Docker?

**Comment by Facinorous-420** [comment]
> I ran into this issue but I am not using Lidarr via Docker. Is it possible to properly mount the download directory to Lidarr if it is not running via Docker?

Yup, this is how I have it set up.

Create the folder `downloads-amd` in your host.
`sudo mkdir /downloads-amd`
Make sure to set it to be owned by the user running your amd docker container (and lidarr):
`sudo chown username:usergroup /downloads-amd`

After this edit your docker-compose file for amd, and under volumes make sure the downloads-amd volume is set like:
`- /downloads-amd:/downloads-amd`

The rest you set normally. Run your amd container.
It should be able to ask lidarr for a list of wanted things, download them, put them in your /downloads/amd/ folder and then tell lidarr to import them. It directly tells lidarr to look in the /downloads-amd/ folder, which you have made so lidarr can access it now and it should be working.
