### ISSUE TITLE
Lidarr "Connect" Notifications on import (i.e. Discord)?

### ISSUE THREAD

**Issue by quorn23** [RandomNinjaAtk/docker-amd#48]
Hi there,

is there a way to have Lidarr trigger the Connections set up in the "Connections" tab of Lidarr?
I have a Discord connection set up, but sadly it doesn't get triggered on importing.

For example
`2021-03-02 14:36:24 :: 9 of 53 :: xxxx :: 2018 :: Album :: xxxxxxx :: LIDARR IMPORT NOTIFICATION SENT! ::xxxxxxxx (2018)-xxxxxxxx,`

in the docker-amd log, but Lidarr never triggers the discord notification.
"On Grab, On Release Import" etc are all enabled.

**Comment by RandomNinjaAtk** [comment]
That's a Lidarr function, so if its not working, you may want to try reporting it there....
