### ISSUE TITLE
ARM Architecture Support

### ISSUE THREAD

**Issue by diabl0w** [RandomNinjaAtk/docker-amd#5]
This is amazing!!! Can we please get support for ARM architecture to run on raspberry pi? That would be awesome

**Comment by RandomNinjaAtk** [comment]
Pull requests welcome

**Comment by diabl0w** [comment]
I actually ended up just buying an atomic pi because i needed an x86 sbc anyway. Not sure if you want to leave this issue open but that closes it on my end, feel free to close if you'd like

**Comment by RandomNinjaAtk** [comment]
This was just implemented
