### ISSUE TITLE
Invoke Scan When Script Sleeps

### ISSUE THREAD

**Issue by justinglock40** [RandomNinjaAtk/docker-amd#50]
Is there a possible way to have the script send a command to scan once the script goes to it's 1 hour sleep. Reason being is that my movies and shows are going over Drive, but the music is on a HDD. So I don't want to have to do full library scans if I can just have the script run a scan on just the Music folder. 

Is this possible?

**Comment by RandomNinjaAtk** [comment]
This doesn't send commands for full library scans...
