### ISSUE TITLE
Stuck at (Analyzing audio loudness: 0%)

### ISSUE THREAD

**Issue by ikrowni** [RandomNinjaAtk/docker-amd#57]
All the files for an entire album seem to have downloaded properly but then i got stuck at (Analyzing audio loudness: 0%)  been stuck here at this for about 20m now.

Edit: I do have an error.txt file in the folder with the songs that says 

`1152196642 | Chris Webby - We Alright | [Errno 2] No such file or directory: '/tmp/deemix-imgs/alb188509252_1200.jpg'`

**Comment by RandomNinjaAtk** [comment]
Sounds like your system is having trouble with replaygain. Try disabling replaygain, ie: replaygain=false
