### ISSUE TITLE
local variable 'result_json' referenced before assignment

### ISSUE THREAD

**Issue by nickashwellrice** [RandomNinjaAtk/docker-amd#59]
I am getting errors when trying to download some tracks, all based around:
"local variable 'result_json' referenced before assignment"
The full error list:
amd  | Dropkick Murphys - Middle Finger local variable 'result_json' referenced before assignment
amd  | Traceback (most recent call last):
amd  |   File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 458, in downloadWrapper
amd  |     result = self.download(extraData, track)
amd  |   File "/usr/lib/python3.8/site-packages/deemix/downloader.py", line 254, in download
amd  |     track = Track().parseData(
amd  |   File "/usr/lib/python3.8/site-packages/deemix/types/Track.py", line 116, in parseData
amd  |     self.retriveFilesizes(dz)
amd  |   File "/usr/lib/python3.8/site-packages/deemix/types/Track.py", line 94, in retriveFilesizes
amd  |     if len(result_json['error']):
amd  | UnboundLocalError: local variable 'result_json' referenced before assignment

Please advise, thanks

**Comment by telans** [comment]
I would report this to the deemix devs rather than here, if possible. I have no idea where their bug tracker is
