### ISSUE TITLE
Not importing to Lidarr

### ISSUE THREAD

**Issue by Protektor-Desura** [RandomNinjaAtk/docker-amd#6]
I am using your docker and I'm not sure what I did wrong. It downloads the albums just fine and connects to Lidarr so it is getting the list of what should be downloaded and connecting to deezer since it downloads. But it doesn't seem to import in to Lidarr.

sudo docker run -d \
 --name lidarr-amd \
 -e PUID=1000 \
 -e PGID=1000 \
 -e TZ=America/Chicago \
 -e AUTOSTART=true \
 -e LidarrUrl=http://192.168.1.10:8686 \
 -e LidarrAPIkey=xxxxxxxxx \
 -e MBRAINZMIRROR=https://musicbrainz.org \
 -e MBRATELIMIT=1 \
 -e ARL_TOKEN=xxxxxxxxx \
 -e LIST=both \
 -e SearchType=both \
 -e Concurrency=3 \
 -e quality=320 \
 -e MatchDistance=10 \
 -e FolderPermissions=755 \
 -e FilePermissions=644 \
 -v /home/protektor/docker/lidarr-amd:/config \
 -v /home/protektor/Downloads/lidarr:/downloads-amd \
 --network="container:qbittorrentvpn" \
 --restart unless-stopped \
 randomninjaatk/amd:latest

That is the exact directory that Lidarr & qBittorrent download in to in my home directory. I also have sonarr and radarr and readarr setup and they all seem to work fine, just AMD isn't importing what it downloads. So I must have something setup incorrectly but I have no idea what that would be. I have also tried just /home/protektor/Downloads which is the same configuration as Lidarr docker but that doesn't seem to work either. Any ideas what I am doing wrong?

**Comment by Protektor-Desura** [comment]
I figured out the issue. My bad. Sorry.

**Comment by MightyRufo** [comment]
How did you fix this?
