### ISSUE TITLE
Lidarr not importing files (not permissions or path related)

### ISSUE THREAD

**Issue by awcrusius** [RandomNinjaAtk/docker-amd#62]
AMD is still importing files, but Lidarr is no longer moving them. included lidarr logs show the following:

`21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 1/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 2/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 3/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 4/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 5/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 6/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 7/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 8/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 9/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 10/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 11/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 12/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 13/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 14/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 15/16
21-9-28 12:20:33.0|Info|ImportDecisionMaker|Reading file 16/16
21-9-28 12:20:33.0|Info|TrackGroupingService|Grouping 16 tracks
21-9-28 12:20:33.0|Info|IdentificationService|Identifying album 1/1
21-9-28 12:20:40.0|Info|ImportApprovedTracks|Importing 0 tracks`

as far as I understand the logs, it appears as if the file is recognized and checked for import but then does not import. multiple files would be upgrades of existing files with most being mp3:320 > FLAC

both AMD and lidarr are running in docker containers on unraid

[Lidarr.txt](https://github.com/RandomNinjaAtk/docker-amd/files/7246828/Lidarr.txt)

**Comment by telans** [comment]
You should be enabling debug logging within lidarr (or trace). But this isn't really docker-amd's issue as far as I see it. Lidarr may just be finding that the album imported for docker-amd has a different track count from the MusicBrainz metadata lidarr depends on

**Comment by RandomNinjaAtk** [comment]
As @telans said, this is a Lidarr issue and nothing to be done here. Most likely lidarr could not find a direct match to import. So it just leaves it there. If you update musicbrainz with a release that matches the downloaded album, it should be able to import in the future.
