### ISSUE TITLE
Alternate Path of extracted content

### ISSUE THREAD

**Issue by Sammydlux** [RandomNinjaAtk/docker-amd#66]
It would be pretty helpfull if we could give the "import" folder an alternate path. 

The issue is, that the download process blocks the auto move script.

**Comment by RandomNinjaAtk** [comment]
Automove script?

**Comment by Sammydlux** [comment]
Oh sorry. I use filebot to move all the files to the right directory f.e. TV Shows, Movies, Music and the script waits every 10 seconds for changing files. And with a bulk of albums this can take many minutes if not hours if done. (Yeah, I know it's a pretty specific use case but would be very helpfull for me).
