### ISSUE TITLE
Umask

### ISSUE THREAD

**Issue by angelss197200** [RandomNinjaAtk/docker-amd#7]
Why the FolderPermissions and FilePermissions parameters when you can use umask?

**Comment by RandomNinjaAtk** [comment]
Idk, it's just how I normally do things... pull requests welcome...

**Comment by angelss197200** [comment]
hey @daPyr0x. The parameter "UMASK_SET", can i use it in the container?

**Comment by daPyr0x** [comment]
@angelss197200 I know that I have it in my docker-compose.yml, but not whether or not it works or does anything.  It's there as a holdover from lidarr-lad, must have missed it when making the jump.  Sorry I can't be of more help.

**Comment by angelss197200** [comment]
closing because the FolderPermissions and FilePermissions parameters are good enough
