### ISSUE TITLE
The script asks ARL to be entered when each song is prepared to be downloaded

### ISSUE THREAD

**Issue by 0xv31an5a1i5** [RandomNinjaAtk/docker-amd#71]
### Basic Info
Script Version 1.5.482
Docker Version 1.1.8
Lidarr Version: 0.8.1.2135

### Issue
Before I could begin, Great work with the script!

I had been testing the library, and recently I came across an issue when downloading the songs. I have supplied the proper ARL to the script and have also downloaded a few songs. However, now that I try to download songs with the script, it asks me for the ARL which looks something like this:
```
2021-12-02 13:10:58 :: 26 of 157 :: Some Artist :: 2021 :: Single :: Some Good Song :: DOWNLOADING :: Some Good Song :: https://deezer.com/album/123456789...
Paste here your arl:
```
When I supply the ARL, The prompt is shown again infinitely.

### More Context
Since the script uses Deemix internally, I did some digging, and it seems like the issue comes up in the [following line](https://github.com/Mushebeq/deemix/blob/c361546f0861ef031204046fa39583675d42fa2e/app.py#L115). Not sure if this is an issue with Deemix or the  Underlying script.

**Comment by RandomNinjaAtk** [comment]
This means your docker config is not correct, make sure you have the full arl key added. Pull a fresh key and verify...

**Comment by justified999** [comment]
> This means your docker config is not correct, make sure you have the full arl key added. Pull a fresh key and verify...

This worked .. although it didn't when I pulled the key and changed the config yesterday - must have mistyped it - doh!
Thanks

**Comment by 0xv31an5a1i5** [comment]
@RandomNinjaAtk 

Yep! Pulling a fresh ARL key worked. Thanks :)
