### ISSUE TITLE
(Another) failed import, doens't exist

### ISSUE THREAD

**Issue by hendymen** [RandomNinjaAtk/docker-amd#74]
Yet another failed import, doens't exist issue/thread.

Although i've tried to follow other reported issues and their solutions, i'm still getting the error message;

`lidarr  | [Warn] DownloadedAlbumsCommandService: Folder/File specified for import scan [/downloads-amd/amd/import/music-number] doesn't exist.
`

I've got an remotely mounted CIFS share in which my music library is located.

My /etc/fstab config for the CIFS share:
`sudo mount -t cifs -o username=administrator,password=****** //192.168.10.21/mount_downloads$ /mnt/mount_downloads
`
`sudo mount -t cifs -o username=administrator,password=****** //192.168.10.21/mount_music$ /mnt/mount_music
`

My config is as following;

/mnt/amd/docker-compose.yml:
`version: "2.1"`
`services:`
`  amd:`
`    image: randomninjaatk/amd`
`    container_name: amd`
`    volumes:`
`      - /mnt/amd/config:/config`
`      - /mnt/mount_downloads:/downloads-amd`
`    environment:`
`      - PUID=0`
`      - PGID=0`

/mnt/lidarr/docker-compose.yml:
`version: "2.1"`
`services:`
`  lidarr:`
`    image: lscr.io/linuxserver/lidarr`
`    container_name: lidarr`
`    environment:`
`      - PUID=0`
`      - PGID=0`
`      - TZ=Europe/London`
`    volumes:`
`      - /mnt/lidarr/config:/config`
`      - /mnt/mount_music:/music`
`      - /mnt/mount_downloads:/downloads`
`      - /mnt/mount_downloads/amd:/downloads-mnt/amd`
`    ports:`
`      - 8686:8686`
`    restart: unless-stopped`

Inside Lidarr the path /downloads-mnt/amd/* is accessible and folders `dlclient` and `amd` are visible.

**Comment by reepje123** [comment]
You need to mount `/mnt/mount_downloads` as `/downloads-amd` in Lidarr.

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
