### ISSUE TITLE
Import to bare-metal (non-docker) Lidarr install

### ISSUE THREAD

**Issue by JRandomHacker** [RandomNinjaAtk/docker-amd#77]
I have Lidarr installed bare-metal on a VM, and AMD running using docker-compose on a separate VM. Both VMs have access to a shared NAS folder, which is mapped to the AMD container as the downloads location. Is it possible to get AMD to trigger an import using the correct path?

**Comment by glmdev** [comment]
Not the author, but I believe the easiest way is to mount the NAS on the `/downloads-amd` path, so when AMD sends the notification to Lidarr, the paths match up. But, there may be another way I'm unfamiliar with.

**Comment by glmdev** [comment]
Ah, seems you can also set the `LIDARRREMOTEPATH` env variable on the amd docker container to map the path.

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
