### ISSUE TITLE
Lidarr is not importing any file

### ISSUE THREAD

**Issue by Schlaumra** [RandomNinjaAtk/docker-amd#83]
I need some help to find the reason why lidarr is not importing the downloaded files.

Lidarr log: https://pastebin.com/mzNzECTq
pass: JNmhTxsGMu

AMD Logs: https://pastebin.com/XcHxeqy7
pass: 8BzDdTyD9D

Lidarr Info:
Version: 0.8.1.2135
Package Version: 0.8.1.2135-ls72 by linuxserver.io
.NET Core: Yes (3.1.13)
Docker: Yes

Both container are running in docker.
Steps:
I checked if the download folder is reachable by both containers: Yes
I checked the log files for an error but I think it looks normal
Important to know:
During the download I restarted the container -> But it seems that amd continues where it left off

**Comment by guipace** [comment]
+1 for this. Also having this issue.

**Comment by MadDucks** [comment]
Did these ever get fixed?

**Comment by RandomNinjaAtk** [comment]
You need to review your lidarr logs. Lidarr should be notified and scanning the files for import. If you turn up the verbosity of the logs in lidarr, you may see what the error/problem is...

Most likely its a volume configuration issue for lidarr/amd or lidarr is unable to match it. If its latter issue, there is nothing that can be done to fix it.

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
