### ISSUE TITLE
Special edition albums problem

### ISSUE THREAD

**Issue by ImjuzCY** [RandomNinjaAtk/docker-amd#85]
I found out that often on Deezer, there is only a "special version" of an album available, while Lidarr doesn't name them so. For example:

`toast to our differences vs toast to our differences (deluxe edition) :: Distance = 17 :: 85072772 :: ERROR :: NO MATCH FOUND`

Is it possible to accept these versions as a valid match?

**Comment by maverick-marq** [comment]
the track count validation might stop this from passing as well. 
I think there should be an option to skip the track count criteria

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
