### ISSUE TITLE
Feature Request: Prefer explicit or non

### ISSUE THREAD

**Issue by Glynax** [RandomNinjaAtk/docker-amd#87]
I'm not sure if this is possible but I've noticed it seems to be random whether it downloads the explicit tracks or not when both are present in deezer, they are flagged on the site as what they are but I would like an env variable to try and prefer downloading all explicit or non explicit tracks for consistencies sake.

**Comment by RandomNinjaAtk** [comment]
All development is being moved to: https://github.com/RandomNinjaAtk/docker-lidarr-extended
