### ISSUE TITLE
Lidarr rejecting and not importing

### ISSUE THREAD

**Issue by robflate** [RandomNinjaAtk/docker-amd#9]
I'm getting lots of albums that Lidarr is rejecting. Yesterday there were over 100;

```
20-8-16 22:15:57.5|Debug|CloseAlbumMatchSpecification|Album match is not close enough: 0.24035812672176307 vs 0.2 [country, tracks]. Skipping
20-8-16 22:15:57.5|Debug|ImportDecisionMaker|Album rejected for the following reasons: [Permanent] Album match is not close enough: 76.0% vs 80% [country, tracks]
```

It's usually because tracks are in a different order on MusicBrainz or the track count is different. I have MatchDistance set to 10 in AMD and set Lidarr to automatically switch to the best release.

Is there anything I can do to prevent this or minimise it? If not, how are people dealing with this other than manually moving the albums and attempting to match them. Thanks.

**Comment by RandomNinjaAtk** [comment]
No, match distance only effects how the script selects which release in the DL client to download. All importing is based on Lidarr's matching engine. 

The only way to improve that would be to update musicbrainz to add a release that matches more closely... 

I would recommend you use this script to help: https://github.com/murdos/musicbrainz-userscripts#deezer_importer

**Comment by robflate** [comment]
Thanks, so if I change `MatchDistance` I will get fewer matches/downloads but Lidarr will be less likely to fail to import the ones AMD does download?

**Comment by RandomNinjaAtk** [comment]
@robflate not necessarily, you can still run into the same issue you were describing. The only thing matchdistance does is compare the DL Client Album Title vs Lidarr's Release Album Title for matching. So lowering, should require the Album titles to match more closely.

But that doesn't account for anything else, like track count differences, metadata differences and etc. Your best bet is to add the release to musicbrainz, with the exact naming, track count, song titles and etc. That will also typically include a link if using the tool above. Which will then allow the script to just use the link to pull it...

**Comment by robflate** [comment]
Thanks. Because AMD and Lidarr both use MusicBrainz, is there any way I could set AMD to only grab a release if it matches one already in MusicBrainz using more of the metadata (track count match is the biggie)?

I considered abandoning Lidarr and just grabbing whatever AMD grabs but the problem is that most tagging tools also rely on MusicBrainz so I'd just end up with the same problem of having lots of music that can't be reliably matched by media servers etc.

I've added quite a few releases to MusicBrainz but I'm getting 30 odd releases a day that Lidarr won't import so I'm not sure I'll ever get them all done! It looks to me like lots of the releases on the streaming services are quite different to the original releases or any versions found on Musicbrainz, I'm assuming depending on what deals they do with which labels, publishers, rights holders etc.

Thanks again for AMD, it's such a great tool!

**Comment by RandomNinjaAtk** [comment]
I typically don't modify the metadata at all for the files, the metadata that is included is fairly comprehensive. And then most platforms, I make sure to set embedded metadata as preferred.

Theres other things, just because you add it to musicbrainz, and my tool can now pull it, you still need to make sure your local Lidarr has the latest artist info. Because it may have not been refreshed to contain the new data you added.

So a lot of it can be a timing issue.

**Comment by robflate** [comment]
I'm not being clear, sorry. Here's what I mean;

For this example we assume all Lidarr artist info is up to date and the artist `Cool Artist` is monitored and their album `Cool Album` is monitored. On MusicBrainz `Cool Album` has 4 different releases with the following differrent track counts, 11, 13, 25 and 26;

- AMD searches and matches the title
- If the AMD variable `TrackCountMatch` is set to true, AMD gets the track count from Deezer and compares it to the 4 releases on MusicBrainz. If the Deezer release has the same track count as one or more of the MusicBrainz releases, a release is downloaded, if not, it is skipped

To be even more strict, AMD could check the release year from Deezer and compare it to MusicBrainz. Of course these additional AMD settings would be optional and off by default.

Perhaps this is not possible with the information AMD can access from Deezer, but it was just a thought.

**Comment by RandomNinjaAtk** [comment]
Currently the method used does not provide a track count, so it's not possible at the moment to filter it that way or I would have. LAD used to do that but it used a more intensive process to do that.

Filtering by year, I believe would be possible in the current setup. 

Right now I'm trying to fix a issue that was caused by a change in the dl client preventing the docker image from building.

**Comment by robflate** [comment]
No problem. Thanks again.
