### ISSUE TITLE
Only singles

### ISSUE THREAD

**Issue by noworthwhile** [RandomNinjaAtk/docker-amd#96]
Hi!

How would I setup the docker container to search only for singles by artists and not for albums?

Also how would I connect the docker with Lidarr which is on a bare metal windows machine?

Thanks!

**Comment by RandomNinjaAtk** [comment]
How would I setup the docker container to search only for singles by artists and not for albums?
Controlled via wanted list
Also how would I connect the docker with Lidarr which is on a bare metal windows machine?
Not designed to work that way....

**Comment by noworthwhile** [comment]
> Controlled via wanted list

I want the albums in my wanted list that are downloaded via torrents.

As for the second point, I will migrate my bare metal install then to docker

**Comment by RandomNinjaAtk** [comment]
You could run 2 lidarr instances, one for singles and one for albums. That way you only connect the AMD to the one that wants singles, not ideal but does work...

**Comment by noworthwhile** [comment]
Solution for the remote importing to a baremetal Lidarr instance on Windows 10:

Create a Samba share on Docker host. Mine is:

`//raspberrypiaddress//home/data/downloads/`

In it resides my `/downloads-amd/amd/import` folder.

Set ENV "LIDARRREMOTEPATH" as follows

`LIDARRREMOTEPATH=\\\\raspberrypiaddress\\pishare\\data\\downloads\\music\\completed\\downloads-amd\\`

Note the double backslashes, because otherwise Lidarr interprets it as en "escapable character" and fails to import.

When setup like this, Lidarr-AMD on Docker on my RaspberryPi downloads and sends notification for import to my Windows machine running baremetal Lidarr.

Maybe you could add this to the wiki?

Thanks.
