### ISSUE TITLE
Could not open file /scripts/temp-lidarr-*.json: No such file or directory

### ISSUE THREAD

**Issue by PN62323424** [RandomNinjaAtk/docker-amd#98]
stdout: cat: /scripts/temp-lidarr-missing.json: No such file or directory
stdout: 2022-05-19 13:56:54 :: FINDING MISSING ALBUMS: 0 Found
stdout: 2022-05-19 13:56:54 :: Downloading cutoff list...
stdout: wget: bad port spec 'http:'
stdout: cat: /scripts/temp-lidarr-cutoff.json: No such file or directory
stdout: 2022-05-19 13:56:54 :: FINDING CUTOFF ALBUMS: 0 Found
stdout: jq: error: Could not open file /scripts/temp-lidarr-*.json: No such file or directory
stdout: ####### DOWNLOAD AUDIO COMPLETE
stdout: 2022-05-19 13:56:54 :: ####### SCRIPT COMPLETE
stdout: 2022-05-19 13:56:54 :: ####### SCRIPT SLEEPING FOR 1h

The log has the following error, this is my docker installation command, where can I set it wrong?

docker create \
  --name=amd \
  -v /mnt/sdb3/docker-amd:/config \
  -v /mnt/sda/media/downloads:/downloads-amd \
  -e PUID=0 \
  -e PGID=0 \
  -e AUTOSTART=true \
  -e SCRIPTINTERVAL=1h \
  -e DOWNLOADMODE=wanted \  
  -e FALLBACKSEARCH=True \
  -e LIST=both \
  -e SearchType=both \
  -e Concurrency=1 \
  -e EMBEDDED_COVER_QUALITY=100 \
  -e FORMAT=MP3 \
  -e BITRATE=320 \
  -e ENABLEPOSTPROCESSING=true \
  -e FORCECONVERT=false \
  -e requirequality=false \
  -e MatchDistance=10 \
  -e replaygain=true \
  -e FolderPermissions=777 \
  -e FilePermissions=777 \
  -e MBRAINZMIRROR=https://musicbrainz.org/ \
  -e MBRATELIMIT=1 \
  -e LidarrUrl=http://10.0.0.75:8686/ \
  -e LidarrAPIkey=XXXXXXXXXXX \
  -e  ARL_TOKEN=XXXXXXXXXXX \
  -e NOTIFYPLEX=false
  -e ALBUM_TYPE_FILTER=COMPILE \
  -e POSTPROCESSTHREADS=1 \
  --restart unless-stopped \
  randomninjaatk/amd

**Comment by RandomNinjaAtk** [comment]
Remove the trailing "/" from -e LidarrUrl=

**Comment by PN62323424** [comment]
> Remove the trailing "/" from -e LidarrUrl=
> 
> ex: -e LidarrUrl=http://10.0.0.75:8686

thank you so much！！

I have been troubled for a night and can't find the reason, and now it can run successfully！
