### ISSUE TITLE
No downloads.. problem with folders

### ISSUE THREAD

**Issue by madroots** [RandomNinjaAtk/docker-amd#99]
Hello,

I have problems figuring out the folders. I believe thats where it goes wrong regarding downloads. 

Here is what my folders looks like:

docker-compose.yml for lidarr:

-  /home/user/docker-music/config:/config
- /home/user/docker-music/downloads-amd:/downloads-amd

and for the AMD i have used

-v "/home/user/docker-music/downloads-amd":"/downloads-amd"
-v "/home/user/docker-music/config/files/":"config"

now, in lidarr its asking me to choose "Root Folder".. which should not be the one where downloads go. what do I do?
No downloading is happening when I choose 'downloads-amd' folder

Appreciate help

**Comment by RandomNinjaAtk** [comment]
Try lidarr-extended

**Comment by madroots** [comment]
Thanks, tried this also, but it would not download anything. Here is what I used to fire up docker: 

docker run -d --name='lidarr-extended' -p '8686':'8686' -v '/home/user/lidarr/config':'/config':'rw' -v '/home/user/lidarr/downloads':'/downloads':'rw' -v '/home/user/lidarr/music':'/music':'rw' -v '/home/user/lidarr/music-videos':'/music-videos':'rw' -e 'PUID=1000' -e 'PGID=1000' -e 'autoStart=true' -e 'configureLidarrWithOptimalSettings=true' -e 'arlToken'='TOKEN' -e 'dlClientSource'='deezer' 'randomninjaatk/lidarr-extended:latest'

Am I doing everything ok? 

When I add new artist, it asks for a name and root folder. so I put name, like artist name and folder "music". 

Is that right? What am I missing? 

Thank you for prompt answer sir.

**Comment by RandomNinjaAtk** [comment]
At the moment, lidarr-extended requires hifi account

**Comment by RandomNinjaAtk** [comment]
just updated lidarr-extended for different bitrates/formats

This container is being discontinued shorlty
